%% A few directives:
%%   * Each tree should always have a depth of 3 layers.
%%   * Nodes labeled with R represent root layers. A nodes represent the ones on
%%     the middle. B represents the tree leaves.
%%   * R nodes define business needs. They provide main answers to the global
%%     question "Why do we need multiprogramming in QPUs in the first place ?"
%%     A nodes defines general solutions to answer business needs. B nodes]
%%     should provide practical example to implement these solutions, thus
%%     defining technical needs we should be looking for when researching and
%%     conceiving solutions.
%%   * When writing description for nodes, one should try to be concise and
%%     straightforward, fitting on two lines (in Mermaid's graph output) at
%%     most.
%%   * We admit the graph is non-exhaustive. We could think of many other
%%     solutions to satisfy different business needs. However, we try to only
%%     stick to solutions that would be the sole responsibility of the
%%     multiprogramming scheduler.

flowchart TD
    R3("Reduce QPU operation costs")
    R1("Minimize user latency")
    R2("Preserve operation quality: gates, measurements...")
    R4("Run secure circuits, on client and service side")
    R5("Deploy and maintain the solution easily")

    R1.A1("Maximize throughput")
    R1.A2("Fast compilation and scheduling")
    R2.A1("Follow circuit compilation best practices")
    R2.A2("Minimize multiprog. impact on fidelity")
    R4.A1("Restrain attack vectors between circuits")
    R4.A2("Identify potential attackers, motives and objectives")
    R5.A1("Solution compatible with familiar tools")
    R5.A2("Deploy with reproducibility")
    R5.A3("Easily reload solution after a crash")
    R5.A4("Orchestrate system as independant modules")

    R1.A1.B1("Share QPU runtime between multiple users")
    R1.A1.B2("Parallelize several circuits from one user: VQE...")
    R1.A2.B1("Acceptable complexity for compilation algorithms")
    R1.A2.B2("Acceptable complexity for scheduling algorithms")
    R1.A2.B3("Offload compilation steps to user: offline compilation")
    R2.A1.B1("Align circuit measurement to occur at the same time")
    R2.A1.B2("Minimize qubits idling time")
    R2.A2.B1("Flexible multiprog.: disable if impact unacceptable")
    R2.A2.B2("Balance between fidelity and throughput")
    R2.A2.B3("Minimize crosstalk impact")
    R4.A1.B1("Isolate circuits execution")
    R5.A1.B1("Recognize popular IR formats: OpenQASM")
    R5.A1.B2("Recognize formats used by popular compilers: Qiskit...")
    R5.A2.B1("Versionize solution on a server : Git...")
    R5.A2.B2("Containerize solution: Docker...")
    R5.A3.B1("If stateless: autoreloading")
    R5.A3.B2("If stateful: convenient persistance for logical state")

    R1    --> R1.A1
    R1    --> R1.A2
    R1.A1 --> R1.A1.B1
    R1.A1 --> R1.A1.B2
    R1.A2 --> R1.A2.B1
    R1.A2 --> R1.A2.B2
    R1.A2 --> R1.A2.B3

    R2    --> R2.A1
    R2    --> R2.A2
    R2.A1 --> R2.A1.B1
    R2.A1 --> R2.A1.B2
    R2.A2 --> R2.A2.B1
    R2.A2 --> R2.A2.B2
    R2.A2 --> R2.A2.B3

    R3    --> R1.A1

    R4    --> R4.A1
    R4    --> R4.A2
    R4.A1 --> R2.A2.B3
    R4.A1 --> R4.A1.B1

    R5    --> R5.A1
    R5    --> R5.A2
    R5    --> R5.A3
    R5    --> R5.A4
    R5.A1 --> R5.A1.B1
    R5.A1 --> R5.A1.B2
    R5.A2 --> R5.A2.B1
    R5.A2 --> R5.A2.B2
    R5.A3 --> R5.A3.B1
    R5.A3 --> R5.A3.B2
